# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: EECS 493
favicon: https://eecs493staff.github.io/eecs493.org/assets/images/eecs493favicon.ico
email:
description: >- # this means to ignore newlines until "baseurl:"
url: "https://eecs493staff.github.io/eecs493.org" # the base hostname & protocol
baseurl: "" # the subpath of your site, e.g. /blog

# Build settings
github: [metadata]
remote_theme: eecs485staff/primer-spec
plugins:
    - jekyll-remote-theme
    - jekyll-optional-front-matter
    - jekyll-readme-index
    - jekyll-relative-links
    - jemoji
    - jekyll-redirect-from
kramdown:
    input: GFM
readme_index:
    remove_originals: true
    with_frontmatter: true
